### ISSUE TITLE
[Request] - Open source ITN database schema

### ISSUE THREAD

**Issue by whankinsiv** [orcfax/itn-api#2]
**Problem:**
As an open-source contributor, I aim to contribute to the ITN API, but the absence of the MySQL table schemas or "CREATE TABLE" commands makes it challenging to design and develop code effectively. Without understanding how the data is stored and structured in the backend, it is difficult to align with the system's requirements and ensure compatibility.

**Request:**
To facilitate contributions and improve development efficiency, I propose the inclusion of the MySQL table schemas in the repository or relevant documentation. Specifically:

1. Provide CREATE TABLE Commands: These should outline the database structure, including columns, data types, constraints, and indexes.
2. Add Sample Data (Optional): Include basic example records to help developers understand expected data formats and relationships.

**Desired Result:**
By sharing the MySQL table structure, contributors will have:

- A clear understanding of the system's data architecture.
- The ability to create local replicas of the database for testing and debugging.
- Confidence that their code aligns with the backend's requirements.

**Comment by ross-spencer** [comment]
thanks for engaging @whankinsiv -- there's a 700MB zip here with some sample data for you or other interested contributors. It's a good idea to look at this, and you can get the schema from the `.schema` command in sqlite3. 

Hope that helps. 

NB. there are staking keys listed in here as the db was used to develop this very basic API -- there's no private data of any sort.
